// front-end/svelte-projects/svelte-5-app/src/routes/cardprojects/Info.svelte
<script lang="ts">
  interface Props {
    framework: string;
    info: string;
    creator: string;
    img: string;
    alt: string;
  }

  let { framework, info, creator, img, alt }: Props = $props();
</script>

<div class="card-container">
  <h1>{framework}</h1>
  <img src={img} {alt} />
  <h2>Creator: {creator}</h2>
  <p>{info}</p>
</div>

<style>
  .card-container {
    max-width: 100%;
    padding: 2rem;
    background-color: #fff;
    color: black;
    margin-top: 2rem;
    border-radius: 2%;
  }
  h1 {
    font-size: 2.3rem;
  }

  img {
    max-width: 12rem;
    height: 40vh;
  }
</style>

// front-end/react-docs-and-projects/react-mini-projects/src/assets/projects/card-project/Info.jsx
import { frameworks } from "./info.js";

export default function Info() {
  return (
    <>
      {frameworks.map((card, i) => (
        <div key={i}>
          <h1> {card.framework}</h1>
          <img src={card.img} alt={card.alt} />
          <h2>{card.creator}</h2>
          <p>{card.info}</p>
        </div>
      ))}
    </>
  );
}
